
# *** This script has been auto-generated by C:\WinPython-64bit-2.7.6.3\python-2.7.6.amd64\Lib\site-packages\aibs\ForagingGui\ScriptGenerator.pyc ***
# *** 	on 2014-04-25 17:30:08.896000   ***


from psychopy import visual, core, event, logging, misc, monitors
import numpy as np
from aibs.Foraging import AdvancedForaging as Foraging
from aibs.Terrain import AdvancedTerrain as Terrain
import socket
import datetime
import aibs.iodaq as iodaq


waitfortrigger = False

NIDev = 'Dev1'
NIPort = 1
NILine = 3
DI0 = iodaq.DigitalInput(NIDev, 0)
DI1 = iodaq.DigitalInput(NIDev, 1)

#PARAMS
params = {'postexpsec': 2, 'shuffle': False, 'syncsqrloc': ((992/2 - 45),(-556/2 + 25)), 
          'encodervsigchannel': 1, 'syncsqr': True, 'rig': 'Widefield', 
          'protocol': None, 'blanksweeps': 0, 'unit': 'B', 'rewardvol': 0.006, 
          'syncsqrfreq': 60, 'runs': 200, 'eyetracker':True,
          'script': 'C:\\WinPython-64bit-2.7.6.3\\python-2.7.6.amd64\\Lib\\site-packages\\aibs\\ForagingGui\\ForagingGui.py', 
          'rewardport': 1, 'sweeplength': 10, 'comments': '', 
          'bgcolor': 'gray', 'nidevice': 'Dev3', 'rewardline': 0, 
          'logdir': 'C:\\AibStim\\MouseLib', 'performanceip': '10.71.219.50', 
          'postsweepsec': 1, 'mouseid': 'MTEST', 'invertdo': False, 
          'rewardtime': 0.006, 'redoblockedsweeps': False, 'rewardlimit': 250, 
          'volumelimit': 1.5, 'performanceport': 9998, 'encodervinchannel': 0, 
          'backupdir': '\\\\aibsdata\\neuralcoding\\Behavior\\Data', 
          'stage': 'Wheel, black foam 6.5 inch diameter.', 'preexpsec': 0, 
          'task': 'Foraging', 'userid': 'Jun', 'miniwindow': False, 
          'timelimit': None, 'mode': 'advanced','lapstartx':-106,'syncsqrsize':(50,50),
          'syncsqrcolorsequence':[1,-1],'syncpulse':True,'syncpulseport':1,'syncpulselines':[1,2]}
params['script']=__file__


#generate movie file name
movFileName = datetime.datetime.now().strftime('%y%m%d%H%M%S') + \
              '-' + params['task'] + '-mouse' + params['mouseid'][1:] + \
              '-' + params['userid']

#TERRAIN
terrain = Terrain()
terrain.correctfreq=1
terrain.current=[-1, 0]
terrain.iscorrect=True
terrain.lapdistance=1000.0
terrain.lapdistancevariability=200
terrain.log=[]
terrain.objectheightDeg=10
terrain.objectwidthDeg=10
terrain.params=[{'relevance': True, 'correct': [-1], 'name': 'Color', 'possible': [-1, 1]}, {'relevance': True, 'correct': [0], 'name': 'Ori', 'possible': [0]}]
terrain.selectiontime=0.2
terrain.sequence=None
terrain.sequence_file=None
terrain.speedgain=0.28
terrain.staircase=None
terrain.units='pix'
terrain.windowwidth=20.0
terrain.windowx=0
terrain.lapstartx = 0
#WINDOW
mon = monitors.Monitor('smartTV')
window = visual.Window(units='pix',monitor = mon, fullscr = False, screen = 1,
	                  color=(0,0,0),size=(992,556),allowGUI=False,pos=(507,436))
#BGSTIMULUS
#STIMULUS
bgStim = visual.GratingStim(window,tex="sin",mask="none",texRes=64, size=[500,500], sf=1, ori = 0, name='grating', autoLog=False, units = 'deg')
bgFrame = {}       
#PARAMETERS
bgSweep={}
bgSweep['Contrast']=([0.8], 3)
bgSweep['Ori']=([0, 90], 0)
bgSweep['Phase']=([0], 4)
bgSweep['PosX']=([0], 1)
bgSweep['PosY']=([0], 2)
bgSweep['SF']=([0.02], 20)
bgSweep['TF']=([0.3], 0)
#FGSTIMULUS
#STIMULUS
monitor = monitors.Monitor('testMonitor')
fgStim = visual.GratingStim(window, tex = None, size = (12,12), units = 'deg', mask = 'circle', color = -1, autoLog=False)
fgFrame = {}
#PARAMETERS
fgSweep={} 

#RUN
g=Foraging(window=window, 
           terrain=terrain,
           params=params,
           bgStim=bgStim,
           bgFrame=bgFrame,
           bgSweep=bgSweep,
           fgStim=fgStim)

if waitfortrigger:
    #check NI signal
    DI = iodaq.DigitalInput(NIDev,NIPort)
    
    lastTTL = DI.Read()[NILine]    
    while True:
        currentTTL = DI.Read()[NILine]
        if (lastTTL == 1) and (currentTTL == 0):
            break
        else:
            lastTTL = int(currentTTL)
    
    print "Triggered, running..."
    
    #updating movie file name
    array0 = DI0.Read()
    array1 = DI1.Read()
    #reverse binary string of digital input port0 line0-7
    str0 = ''.join(map(str,array0))[::-1]
    #reverse binary string of digital input port1 line0-2
    str1 = ''.join(map(str,array1))[-2::-1]
    fileNumber = int(str1 + str0,2) 
    movFileName = movFileName + '-' + str(int(fileNumber))    
    
    g.run(movFileName, str(int(fileNumber)))
    
else:
    print "running without trigger..."
    
    g.run(movFileName)
    
